# this is a catalog entity descriptor file for our Backstage instance (https://backstage.wistia.cloud)

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Wistia-React
  description: SSR and SEO friendly React components for Wistia embeds
  annotations:
    github.com/project-slug: wistia/wistia-react
    backstage.io/techdocs-ref: dir:.
  tags:
    - lang#javascript
    - pkg#npm
spec:
  type: library
  owner: publish-embeds
  lifecycle: production
